name = "private-folio"
compatibility_date = "2024-04-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "" # Will be filled by user during deployment
