name = "private-folio"
compatibility_date = "2024-04-01"
main = ".vercel/output/static/_worker.js"
assets = { directory = ".vercel/output/static" }

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "" # Will be filled by user during deployment
